### ISSUE TITLE
Does not work with postcss 8

### ISSUE THREAD

**Issue by boris-petrov** [jeffjewiss/ember-cli-postcss#659]
I updated `autoprefixer` to version 10 (which uses postcss 8) and then ran `ember serve`. The error:

```
Build Error (PostcssCompiler)

[object Object] is not a PostCSS plugin
```

<details>
  <summary>The details:</summary>

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/boris/project/node_modules/postcss/lib/processor.js:168:15)
    at Processor.use (/home/boris/project/node_modules/postcss/lib/processor.js:88:45)
    at /home/boris/project/node_modules/broccoli-postcss-single/index.js:69:15
    at Array.forEach (<anonymous>:null:null)
    at PostcssCompiler.build (/home/boris/project/node_modules/broccoli-postcss-single/index.js:59:16)
    at /home/boris/project/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

  - code: [undefined]
  - codeFrame: [object Object] is not a PostCSS plugin
  - errorMessage: [object Object] is not a PostCSS plugin
        at PostcssCompiler
-~- created here: -~-
    at PostcssCompiler.Plugin (/home/boris/project/node_modules/broccoli-plugin/index.js:7:31)
    at PostcssCompiler.CachingWriter [as constructor] (/home/boris/project/node_modules/broccoli-caching-writer/index.js:18:10)
    at new PostcssCompiler (/home/boris/project/node_modules/broccoli-postcss-single/index.js:23:17)
    at /home/boris/project/node_modules/ember-cli-postcss/index.js:36:12
    at Array.map (<anonymous>:null:null)
    at PostcssPlugin.toTree (/home/boris/project/node_modules/ember-cli-postcss/index.js:33:36)
    at /home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>:null:null)
    at processPlugins (/home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at module.exports.preprocessCss (/home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:156:10)
    at DefaultPackager.packageStyles (/home/boris/project/node_modules/ember-cli/lib/broccoli/default-packager.js:558:32)
    at EmberApp._legacyPackage (/home/boris/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1619:44)
    at EmberApp.toTree (/home/boris/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:27)
    at module.exports (/home/boris/project/ember-cli-build.js:315:14)
    at Builder.readBuildFile (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/home/boris/project/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at /home/boris/project/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Class.run (/home/boris/project/node_modules/ember-cli/lib/commands/test.js:197:7)
    at /home/boris/project/node_modules/ember-cli/lib/cli/cli.js:204:32
    at CLI.run (/home/boris/project/node_modules/ember-cli/lib/cli/cli.js:251:14)
    at module.exports (/home/boris/project/node_modules/ember-cli/lib/cli/index.js:145:12)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: [object Object] is not a PostCSS plugin
        at PostcssCompiler
-~- created here: -~-
    at PostcssCompiler.Plugin (/home/boris/project/node_modules/broccoli-plugin/index.js:7:31)
    at PostcssCompiler.CachingWriter [as constructor] (/home/boris/project/node_modules/broccoli-caching-writer/index.js:18:10)
    at new PostcssCompiler (/home/boris/project/node_modules/broccoli-postcss-single/index.js:23:17)
    at /home/boris/project/node_modules/ember-cli-postcss/index.js:36:12
    at Array.map (<anonymous>:null:null)
    at PostcssPlugin.toTree (/home/boris/project/node_modules/ember-cli-postcss/index.js:33:36)
    at /home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>:null:null)
    at processPlugins (/home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at module.exports.preprocessCss (/home/boris/project/node_modules/ember-cli-preprocess-registry/preprocessors.js:156:10)
    at DefaultPackager.packageStyles (/home/boris/project/node_modules/ember-cli/lib/broccoli/default-packager.js:558:32)
    at EmberApp._legacyPackage (/home/boris/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1619:44)
    at EmberApp.toTree (/home/boris/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:27)
    at module.exports (/home/boris/project/ember-cli-build.js:315:14)
    at Builder.readBuildFile (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/boris/project/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/home/boris/project/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at /home/boris/project/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Class.run (/home/boris/project/node_modules/ember-cli/lib/commands/test.js:197:7)
    at /home/boris/project/node_modules/ember-cli/lib/cli/cli.js:204:32
    at CLI.run (/home/boris/project/node_modules/ember-cli/lib/cli/cli.js:251:14)
    at module.exports (/home/boris/project/node_modules/ember-cli/lib/cli/index.js:145:12)

-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: PostcssCompiler
  - originalErrorMessage: [object Object] is not a PostCSS plugin
  - stack: Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/boris/project/node_modules/postcss/lib/processor.js:168:15)
    at Processor.use (/home/boris/project/node_modules/postcss/lib/processor.js:88:45)
    at /home/boris/project/node_modules/broccoli-postcss-single/index.js:69:15
    at Array.forEach (<anonymous>:null:null)
    at PostcssCompiler.build (/home/boris/project/node_modules/broccoli-postcss-single/index.js:59:16)
    at /home/boris/project/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/boris/project/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
</details>

**Comment by jeffjewiss** [comment]
Thanks for reporting this.

Looks like it will require updating postcss to version 8 in `broccoli-postcss` and `broccoli-postcss-single` and releasing a new major version to support the new plugin API.

Until that update is done `ember-cli-postcss` won't be able to support postcss 8 style plugins.

**Comment by josemarluedke** [comment]
Looking forward to using v8 as well.

**Comment by optikalefx** [comment]
Also looking forward to v8

**Comment by jeffjewiss** [comment]
`ember-cli-postcss` v7 has been released, which supports Postcss v8. Please try upgrading and open a new issue if there are any problems.

*Note: for those using `autoprefixer` v10.0.0 caused a maximum call stack error while testing. Please try using v10.0.1.*
