### ISSUE TITLE
Addon using @tailwindcss/jit: ENOENT: no such file or directory, stat 'assets/vendor.css'

### ISSUE THREAD

**Issue by shadyvd** [jeffjewiss/ember-cli-postcss#765]
When trying to use @tailwindcs/jit in an Ember Addon, the followinf error occurs:

=================================================================================
ENV Summary:
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - ~/.config/npm/bin/ember
  - serve
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /usr/bin/zsh
  PATH:
  - ~/.config/npm/bin
  - ~/bin
  - /usr/local/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/local/sbin
  - /usr/bin/site_perl
  - /usr/bin/vendor_perl
  - /usr/bin/core_perl
  PLATFORM: linux x64
  FREEMEM: 6214692864
  TOTALMEM: 16277942272
  UPTIME: 10782.09
  LOADAVG: 0.78,0.98,1.32
  CPUS:
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 1200
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 1200
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 3407
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 1200
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 2542
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 2395
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 1200
  - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz - 1200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 6.0.1
  - modules: 93
  - napi: 8
  - nghttp2: 1.43.0
  - node: 16.2.0
  - openssl: 1.1.1k
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.41.0
  - v8: 9.0.257.25-node.16
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, stat 'assets/vendor.css'
    at Object.statSync (node:fs:1527:3)
    at trackModified (~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/lib/setupContext.js:230:26)
    at ~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/lib/setupContext.js:725:38
    at ~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/index.js:37:49
    at LazyResult.runOnRoot (~/Work/twyr/code/multi-dsl/node_modules/postcss/lib/lazy-result.js:333:16)
    at LazyResult.runAsync (~/Work/twyr/code/multi-dsl/node_modules/postcss/lib/lazy-result.js:385:26)
    at async Object.processString (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/strategies/default.js:7:22)
    at async invoke (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:84:12)
    at async module.exports.processFile (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:393:22)
    at async module.exports.processAndCacheFile (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:369:20)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, stat 'assets/vendor.css'
  - errorMessage: assets/vendor.css: ENOENT: no such file or directory, stat 'assets/vendor.css'
        in /tmp/broccoli-16585zgjE4fG2GaxF/out-160-broccoli_merge_trees_packaged_styles
        at 
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: assets/vendor.css
    - line: [undefined]
    - treeDir: /tmp/broccoli-16585zgjE4fG2GaxF/out-160-broccoli_merge_trees_packaged_styles
  - message: assets/vendor.css: ENOENT: no such file or directory, stat 'assets/vendor.css'
        in /tmp/broccoli-16585zgjE4fG2GaxF/out-160-broccoli_merge_trees_packaged_styles
        at 
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: 
  - originalErrorMessage: ENOENT: no such file or directory, stat 'assets/vendor.css'
  - stack: Error: ENOENT: no such file or directory, stat 'assets/vendor.css'
    at Object.statSync (node:fs:1527:3)
    at trackModified (~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/lib/setupContext.js:230:26)
    at ~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/lib/setupContext.js:725:38
    at ~/Work/twyr/code/multi-dsl/node_modules/@tailwindcss/jit/src/index.js:37:49
    at LazyResult.runOnRoot (~/Work/twyr/code/multi-dsl/node_modules/postcss/lib/lazy-result.js:333:16)
    at LazyResult.runAsync (~/Work/twyr/code/multi-dsl/node_modules/postcss/lib/lazy-result.js:385:26)
    at async Object.processString (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/strategies/default.js:7:22)
    at async invoke (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:84:12)
    at async module.exports.processFile (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:393:22)
    at async module.exports.processAndCacheFile (~/Work/twyr/code/multi-dsl/node_modules/broccoli-postcss/node_modules/broccoli-persistent-filter/lib/index.js:369:20)

=================================================================================
PostCSS is configured with the options given below:

```
const CssImport = require('postcss-import');
const Nesting = require('postcss-nesting');
const PresetEnv = require('postcss-preset-env');
const Reporter = require('postcss-reporter');
const StyleLint = require('stylelint');
const TailwindCss = require('@tailwindcss/jit');

const postcssOptions = {
	'compile': {
		'cacheInclude': [/.*\.(css|scss|sass|less|hbs)$/, /.tailwind\.js$/],
		'enabled': true,
		'plugins': [{
				'module': CssImport,
				'options': {
					'plugins': [StyleLint]
				}
			},
			{
				'module': Nesting,
				'options': {}
			},
			{
				'module': TailwindCss,
				'options': {
					'config': './tailwind_css/tailwind.config.js'
				}
			},
			{
				'module': PresetEnv,
				'options': {
					'stage': 3
				}
			},
			{
				'module': Reporter,
				'options': {
					'clearReportedMessages': true
				}
			}
		]
	},
	'filter': {
		'cacheInclude': [/.*\.(css|scss|sass|less|hbs)$/, /.tailwind\.js$/],
		'enabled': true,
		'plugins': [{
				'module': CssImport,
				'options': {
					'plugins': [StyleLint]
				}
			},
			{
				'module': Nesting,
				'options': {}
			},
			{
				'module': TailwindCss,
				'options': {
					'config': './tailwind_css/tailwind.config.js'
				}
			},
			{
				'module': PresetEnv,
				'options': {
					'stage': 3
				}
			},
			{
				'module': Reporter,
				'options': {
					'clearReportedMessages': true
				}
			}
		]
	}
};

```
=================================================================================

Notes:
1. Exactly the same configuration / package.json works if the non-jit version of tailwindcss is used.
2. Triggering a rebuild does not force tailwindcss to actual re-build, unless ```ember serve``` is killed and re-started.

**Comment by jeffjewiss** [comment]
My suspicion is that Tailwind's JIT feature is incompatible with Broccoli due to how Broccoli creates temporary directories on the filesystem and serves the CSS files from there. It may be possible to get it to work with a more custom integration, but I don't currently have the time available to test this.
